name: Promote-to-qa
on:
  workflow_dispatch:
    inputs:
      rb-version:
        description: 'Release bundle version'     
        required: true
permissions:
  id-token: write
  contents: read

jobs:
  Promote-to-qa-and-test:
    environment: Jfrog
    runs-on: ubuntu-latest
    env:
      PROMOTE_REPO_NAME: ptfl-oci-dev-local
      JF_PROJECT: ptfl
    steps:
    
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup JFrog CLI 
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: https://${{ vars.JF_URL }}/
          JF_PROJECT: ${{ vars.JF_PROJECT }}
        with:
            oidc-provider-name: ptfl-github
            oidc-audience: ptfl-aud

      - name: Promote to Test
        run: |
          jf release-bundle-promote ptt25-b-kryptostream-app-release-bundle ${{ inputs.rb-version }} QA --signing-key ${{ secrets.RB_KEY }} --sync=true --project ${JF_PROJECT}
   
