  - name: Promote to Test
        run: |
          if [ "${{ env.RESULT }}" == "true" ]; then
            jf release-bundle-promote ${{ github.actor }}-evd-flow ${{ inputs.rb-version }} QA --signing-key ${{ secrets.RB_KEY }} --sync=true --project ${JF_PROJECT}
            echo "🚀 Succesfully promoted to \`QA\` environemnt" >> $GITHUB_STEP_SUMMARY
          else
            opa eval --input ./evidence_graph.json --data policy/policy.rego "data.policy.output" | jq '.result[0].expressions[0].value'
            echo "Fail promotion policy check" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi
